### ISSUE TITLE
_spiflash_clz() can't work right?

### ISSUE THREAD

**Issue by suhacen** [pellepl/spiflash_driver#7]
I don't know if I understand right or not, _spiflash_clz() can't work correctly.

assuming the addr is 4096, _spiflash_clz(4096) = 249, it gonna have an overflow error at array MultiplyDeBruijnBitPosition[].

**Comment by pellepl** [comment]
The index of MultiplyDeBruijnBitPosition is bitshifted right 27 bits, leaving 5 bits. This ranges from 0 to 31 so yes, it works

**Comment by suhacen** [comment]
Yes, you are correct, I made a mistake about the type of integer.
